---
title: "neutro analysis"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#TODO add root folder using knitr root.dir()
```


```{r message = FALSE, warning=FALSE}
library(ggplot2)
library(RVenn)

# load the data and visualization functions
source("global.R")
source("../utils/visualization_functions.R")
```

Normalised spectral count per group and total, add columns to dataframe
```{r}
# Z-score normalisation, by group and total
all_data_neutro <- all_data_neutro %>% group_by(bait, condition) %>% mutate(grouped_z_score_spectral = scale(spectral_count))
all_data_neutro <- all_data_neutro %>% mutate(z_score_spectral = scale(spectral_count))
```


Summary statistics Neutro
```{r}
table(all_data_neutro$bait)
table(all_data_neutro$condition)
```


```{r}
plot_spectral_bait_condition_using_uniprot('P36415', 'neutro')
plot_spectral_bait_condition_using_uniprot('GST', 'neutro')
plot_spectral_bait_condition_using_uniprot('Q54YT4', 'neutro')
```

